name: Pull Request
on:
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
        name: npm  install
      - run: npm run build --mode production
        name: npm run build
      - run: npm run test:unit --passWithNoTests
        name: npm run test