name: Pull Request
on:
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
        name: yarn
      - run: yarn build --mode production
        name: yarn build
      - run: yarn test:unit --passWithNoTests
        name: yarn test